QuizAssessment/Models/Assessment.cs
using System.ComponentModel.DataAnnotations;

namespace QuizAssessment.Models
{
    public class Assessment
    {
        [Key]
        public string Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public float Grade { get; set; }
    }
}

QuizAssessment/Models/ErrorViewModel.cs
namespace QuizAssessment.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

QuizAssessment/Models/Quiz.cs
using System.ComponentModel.DataAnnotations;

namespace QuizAssessment.Models
{
	public class Quiz
	{
		[Key]
		public int Id { get; set; }
		[Required]
		public string Question { get; set; }
		[Required]
		public string Answer { get; set; }
	}
}

QuizAssessment/ViewModels/QuizAssessmentViewModels.cs
using QuizAssessment.Models;
using System.Diagnostics.CodeAnalysis;

namespace QuizAssessment.ViewModels
{
	public class QuizAssessmentViewModels
	{
		[AllowNull]
		public List<Quiz>	Quiz { get; set; }
		[AllowNull]
		public Assessment Assessment { get; set; }
	}
}

QuizAssessment/Controllers/AssessmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuizAssessment.Data;
using QuizAssessment.Models;
using QuizAssessment.ViewModels;

namespace QuizAssessment.Controllers
{
    public class AssessmentController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AssessmentController(ApplicationDbContext context) {  _context = context; }
        // GET: AssessmentController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AssessmentController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AssessmentController/Create
        public ActionResult Exam()
        {
            var quiz=_context.Quizzes.ToList();
            var viewModel = new QuizAssessmentViewModels
            {
                Quiz = quiz,
            };
            return View(viewModel);
        }

        // POST: AssessmentController/Create
        [HttpPost]
       public IActionResult Create(List<string> answer)
        {
            var obj = new Assessment { "Hong Kien", 9.0f};
            if (answer[0]=="2") _context.Add(obj);
			return RedirectToAction("Index");
        }
    }
}

QuizAssessment/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QuizAssessment.Models;
using System.Diagnostics;

namespace QuizAssessment.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

QuizAssessment/Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;
using QuizAssessment.Data;
using QuizAssessment.Models;

namespace QuizAssessment.Controllers
{
	public class QuizController : Controller
	{
		private readonly ApplicationDbContext _context;
		public QuizController(ApplicationDbContext db) { 
			_context = db;
		}
        public IActionResult Index()
		{		
			var objQuzList=_context.Quizzes.ToList();
			return View(objQuzList);
		}
		public IActionResult Create()
		{
			return View();
		}
		public IActionResult Exam()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Create(Quiz obj) { 
			if (ModelState.IsValid)
			{
                _context.Quizzes.Add(obj);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
			return View();
		}
		public IActionResult Edit(int? id)
		{
            if ((id==null)||id==0)
            {
				return NotFound();
            }
			Quiz foundedQuiz=_context.Quizzes.Find(id);
			if(foundedQuiz==null)
			{
				return NotFound();
			}
            return View(foundedQuiz);
		}
		[HttpPost]
		public IActionResult Edit(Quiz obj) {
			if(ModelState.IsValid)
			{
				_context.Quizzes.Update(obj);
				_context.SaveChanges();
				return RedirectToAction("Index");
			}
			return View();
		}
        [HttpPost]
        public IActionResult Delete(int id)
        {
            Quiz obj = _context.Quizzes.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _context.Quizzes.Remove(obj);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

QuizAssessment/Views/Assessment/Exam.cshtml
@model QuizAssessmentViewModels;

<div>
	<form method="post" asp-controller="Assessment" asp-action="Create">
		@for (int i=0; i<Model.Quiz.Count();i++)
		{
			<div>
				<h3>@Model.Quiz[i].Question</h3>
				<input type="text" name="answer[@i]"/>
			</div>
		}
		<button class="btn btn-primary">Submit Answer</button>
	</form>
</div>

QuizAssessment/Views/Assessment/Index.cshtml
@model List<Assessment>
<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h1 class="text-primary">Assessment List</h1>
        </div>

    <table class="table table-border table-striped">
        <thead>
            <tr class="text-center">
                <th>
                    Name
                </th>
                <th>
                    Grade
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody class="text-center">
            
            @if (Model!=null){ @foreach (var obj in Model.OrderBy(u => u.Id))
            {
                <tr>
                    <td>@obj.Name</td>
                    <td>@obj.Grade</td>
                    <td style="width:100px; text-align:center">
                        <div class="w-100 btn-group d-flex justify-content-center align-items-center" role="group">
                            <a asp-controller="Assessment" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2" style="width:150px">Edit</a>
                            <form asp-controller="Assessment" asp-action="Delete" method="post">
                                <input type="hidden" name="id" value="@obj.Id" />
                                <button type="submit" class="btn btn-danger mx-2 ">Delete</button>
                            </form>
                        </div>
                    </td>
                </tr>
            }}
        </tbody>
    </table>
</div>

QuizAssessment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

QuizAssessment/Views/Quiz/Create.cshtml
@model Quiz

<form method="post" asp-action="Create">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Quiz</h2>
		</div>
		<div class="mb-3" style="display:flex; flex-direction:column">
			<label>Question</label>
			<input asp-for="Question" placeholder="Enter question." />
			<span asp-validation-for="Question" class="text-danger"></span>
		</div>
		<div class="mb-3" style="display:flex; flex-direction:column">
			<label>Answer</label>
			<input asp-for="Answer" placeholder="Enter answer." />
			<span asp-validation-for="Question" class="text-danger"></span>
		</div>
		<div class="row">
			<div class="col-6 col-md-3">
				<button type="submit" class="btn btn-primary" style="width:100%;">Create</button>
			</div>
			<div class="col-6 col-md-3">
				<a asp-controller="Quiz" asp-action="Index" class="btn btn-outline-secondary" style="width:100%">Back To List</a>
			</div>
		</div>
	</div>
</form>
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial"/>
	}
}

QuizAssessment/Views/Quiz/Edit.cshtml
@model Quiz

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Quiz</h2>
		</div>
		<div class="mb-3" style="display:flex; flex-direction:column">
			<label>Question</label>
			<input asp-for="Question" placeholder="Enter question." />
			<span asp-validation-for="Question" class="text-danger"></span>
		</div>
		<div class="mb-3" style="display:flex; flex-direction:column">
			<label>Answer</label>
			<input asp-for="Answer" placeholder="Enter answer." />
			<span asp-validation-for="Question" class="text-danger"></span>
		</div>
		<div class="row">
			<div class="col-6 col-md-3">
				<button type="submit" class="btn btn-primary" style="width:100%;">Update</button>
			</div>
			<div class="col-6 col-md-3">
				<a asp-controller="Quiz" asp-action="Index" class="btn btn-outline-secondary" style="width:100%">Back To List</a>
			</div>
		</div>
	</div>
</form>
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

QuizAssessment/Views/Quiz/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<Quiz> 
<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h1 class="text-primary">Quiz List</h1>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Quiz" asp-action="Create" class="btn btn-primary">Add</a>
        </div>
    </div>
<table class="table table-border table-striped">
    <thead>
        <tr class="text-center">
            <th>
                Question
            </th>
            <th>
                Answer
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
        <tbody class="text-center">

        @foreach(var obj in Model.OrderBy(u=>u.Id))
            {
                <tr>
                    <td>@obj.Question</td>
                    <td>@obj.Answer</td>
                    <td style="width:100px; text-align:center">
                        <div class="w-100 btn-group d-flex justify-content-center align-items-center" role="group">
                            <a asp-controller="Quiz" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2" style="width:150px">Edit</a>
                            <form asp-controller="Quiz" asp-action="Delete" method="post">
                                <input type="hidden" name="id" value="@obj.Id" />
                                <button type="submit" class="btn btn-danger mx-2 ">Delete</button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
    </tbody>
</table>
</div>

QuizAssessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuizAssessment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuizAssessment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QuizAssessment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quiz" asp-action="Index">Quizzes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assessment" asp-action="Index">Assessment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assessment" asp-action="Exam">Take Assessment</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - QuizAssessment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>